name: blender
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.2
  - pip=22.2.2
  - pyzmq=24.0.1
  - pip:
    - https://github.com/wengflow/rpg_esim/releases/download/v1.0/bpy-3.4.0a0-cp310-cp310-manylinux_2_31_x86_64.whl
